user www-data;

events {}

http {

  include mime.types;

  server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    
    # location = /images/thumb.png {
      # add_header my_header "Hello World.";
    # }

    location ~* \.(css|js|jpg|png)$ {
      add_header Cache-Control public;
      add_header Pragma public;
      add_header Vary Accept-Encoding;
      expires 1M;
    }

  }
}
