events {}

http {

  include mime.types;

  upstream php_servers {
    # ip_hash;
    # least_conn;
    server localhost:9001;
    server localhost:9002;
    server localhost:9003;
  }

  server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location / {
      proxy_pass 'http://php_servers';
    }
    
  }
}