events {}

http {

  include mime.types;

  server {
    listen 80;
    server_name localhost;
    
    # Exact match
    location = /hello {
      return 200 '"/hello" - Exact match';
    }

    # Case sensitive
    location ~ /hi5 {
      return 200 '"/hi5" - Case sensitive';
    }    

    # Case insensitive
    location ~* /hi6 {
      return 200 '"/hi6" - Case insensitive';
    }

    # Regular Expression - Case sensitive
    location ~ /hello[1-9] {
      return 200 '"/hello" - Regular Expression';
    }

    # Regular Expression - Case insensitive
    location ~* /greeting[1-9] {
      return 200 '"/greeting" - Regular Expression';
    }
    
  }
}
