events {}

http {

  include mime.types;

  server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location /authen {
      access_log /var/log/nginx/authen.access.log;
      # access_log off;
      return 200 "Welcome to authen.";
    }

  }
}
