user www-data;

load_module /etc/nginx/modules/ngx_http_image_filter_module.so;

events {}

http {

  include mime.types;

  server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    
    location ~\.jpg$ {
      image_filter rotate 90;
    }
    
  }
}
