events {}

http {

  include mime.types;

  server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    # try_files /images/thumb.png /hello;
    try_files $uri /images/thumdb.png /hello /error_404;

    location /error_404 {
      return 404 "Sorry, File not found.";
    }

    location /hello {
      return 200 "Hello";
    }

   

  }
}
