services:
    php:
        build:
            context: ./php
        ports:
            - "8080:80"
        volumes:
            - ./php/site:/var/www/html/
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
        secrets:
            - db_password
    phpmyadmin:
        depends_on:
        - db
        image: phpmyadmin
        ports:
        - 8888:80

secrets:
    db_password:
        file: ./secrets/db_password.txt